name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  tests:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s tests/unit -p "test_*.py"
      - name: Run integration tests with coverage
        run: |
          coverage run -a -m unittest discover -s tests/integration -p "test_*.py"
        env:
          ALPHA_VANTAGE_API_KEY: IT7IZA3P82EG5G5M
          VERIFY_SSL: true
      - name: Generate coverage report
        run: |
          coverage xml -o coverage.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}